version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:2.365'
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
    restart: 'on-failure'

volumes:
  jenkins_home:




